[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wexample-filestate-git"
version = "0.0.8"
description = "An extension for \"filestate\" package, which adds GIT management operations."
readme = { file = "README.md", content-type = "text/markdown" }
authors = [{ name = "weeger", email = "contact@wexample.com" }]
license = { text = "MIT" }
requires-python = ">=3.6"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "pydantic",
    "requests",
    "wexample-filestate",
    "wexample-helpers",
    "wexample-helpers-git",
]

[project.urls]
homepage = "https://github.com/wexample/python-filestate-git"
